[project]
name = "pyclassic"
description = "Minecraft Classic Protocol implementation in Python"
version = "2023.dev"
authors = [
    { name = "matthilde" },
    { name = "yourfriend" }
]
dependencies = ["requests"]
